DROP TABLE IF EXISTS orderitems;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	username VARCHAR(100) PRIMARY KEY NOT NULL,
	password VARCHAR(100) NOT NULL
);

INSERT INTO users (username, password)
VALUES ('admin', '12345');

CREATE TABLE materials (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(100) NOT NULL,
	size DECIMAL(7, 2) NOT NULL,
    price double(8,2) NOT NULL
);

CREATE TABLE orders (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	customer_name VARCHAR(100) NOT NULL,
	customer_email VARCHAR(100) NOT NULL,
	customer_phone VARCHAR(100) NOT NULL, 
	isFinished BOOLEAN NOT NULL,
	width INTEGER NOT NULL,
	length INTEGER NOT NULL,
	height INTEGER NOT NULL
);

CREATE TABLE orderitems (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	order_id INTEGER NOT NULL REFERENCES orders(id),
	material_id INTEGER NOT NULL REFERENCES materials(id),
	quantity INTEGER NOT NULL
);



